### ISSUE TITLE
Regent: compilation failure with interfering privileges

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1142]
This would be a runtime error even if it compiled; but even so, we shouldn't be crashing in the compiler. I think this is occurring because the compiler assumes all region arguments with privileges are index accesses.

```lua
import "regent"

task f(r : region(int), s : region(int)) where reads writes(r), reads (s) do
end

task main()
  var r = region(ispace(ptr, 5), int)
  var p = partition(equal, r, ispace(int1d, 3))
  fill(r, 0)

  for i = 0, 3 do
    f(p[i], r)
  end
end
regentlib.start(main)
```

Note this also makes RDIR unhappy so you need to run with `-fflow 0` to see it:

```
$ ./regent.py test_bug_index_launch_interference.rg -fflow 0
...egion/language/src/regent/optimize_index_launches.t:41: symbol has no field 'value' (in lookup)
stack traceback:
	[C]: in function 'error'
	...legion/language/src/regent/std_base.t:901: in function '__index'
	...legion/language/src/regent/optimize_index_launches.t:41: in function 'get_partition_symbol'
	...legion/language/src/regent/optimize_index_launches.t:1178: in function 'optimize_loop_body'
	...legion/language/src/regent/optimize_index_launches.t:1525: in function 'map_node_postorder'
	...legion/language/src/common/ast.t:520: in function 'map_node_postorder'
	...legion/language/src/common/ast.t:511: in function 'map_node_postorder'
	...legion/language/src/common/ast.t:511: in function 'top_task'
	...legion/language/src/regent/optimize_index_launches.t:1658: in function <...legion/language/src/regent/optimize_index_launches.t:1652>
	...legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
	...legion/language/src/regent/passes.t:52: in function <...legion/language/src/regent/passes.t:48>
	test_bug_index_launch_interference.rg:6: in main chunk
```

**Comment by elliottslaughter** [comment]
@rupanshusoi just FYI, I think this was introduced in https://github.com/StanfordLegion/legion/pull/1097.
