### ISSUE TITLE
All tests fail with "invalid processor handle" on f28

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#350]
Working on getting legion-18.02.0 updated in fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1541580), bump in Fedora 27 worked without a problem (https://koji.fedoraproject.org/koji/taskinfo?taskID=24687183), but in Fedora 28 all tests fail with:
```
/builddir/build/BUILD/legion-legion-18.02.0/runtime/realm/runtime_impl.cc:2402: Realm::ProcessorImpl* Realm::RuntimeImpl::get_processor_impl(Realm::ID): Assertion `0 && "invalid processor handle"' failed.
```
Details here: https://koji.fedoraproject.org/koji/taskinfo?taskID=24687199

All packages are build from the same source using the same options, but f28 comes with gcc-8 and many other updates incl. hwloc.

**Comment by streichler** [comment]
@junghans did the 17.10 release work with fedora 28, or have you only tried 18.02?

**Comment by lightsighter** [comment]
At least some of the failures are compilation failures and not runtime errors:

In file included from /usr/include/openmpi-s390x/gasnet_atomicops.h:152,
                 from /usr/include/openmpi-s390x/gasnet.h:203,
                 from /builddir/build/BUILD/legion-legion-18.02.0/runtime/realm/mem_impl.cc:30:
/usr/include/openmpi-s390x/gasnet_atomic_bits.h:302:6: error: #error "GASNETI_USE_COMPILER_ATOMICOPS for unknown or unsupported compiler"
     #error "GASNETI_USE_COMPILER_ATOMICOPS for unknown or unsupported compiler"

**Comment by junghans** [comment]
@streichler, 17.10 has fine, but I retrigger build in the new enviorment just to check: 
https://koji.fedoraproject.org/koji/taskinfo?taskID=24715299

@lightsighter, I had only looked at the `x86_64` build, the error on `s390x` means gasnet needs a rebuild as well. I will do that later.

**Comment by junghans** [comment]
Ok, it seems to be the f28, which makes it fail not 18.02! Still same error even with 17.10!

**Comment by junghans** [comment]
I was able to reproduce the problem locally using:
```
mock -r fedora-rawhide-x86_64 rebuild legion-18.02.0-1.fc27.src.rpm
```

**Comment by lightsighter** [comment]
@junghans Can you get a backtrace for one of the crashes please?

**Comment by streichler** [comment]
I have reproduced this in a docker image.  It appears to be related to gcc 8 and how it is "optimizing" some code.  Trying to figure out how to get it to produce the correct code now.

**Comment by junghans** [comment]
With the following Dockerfile:
```
FROM fedora:rawhide
RUN dnf install -y gasnet-devel git cmake redhat-rpm-config gcc-c++ gdb hwloc-devel
RUN git clone https://github.com/StanfordLegion/legion.git
WORKDIR legion/build
ENV CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
ENV CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
ENV LDFLAGS='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed'
RUN cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DLegion_USE_HWLOC=ON -DLegion_BUILD_EXAMPLES=ON -DCOMPILER_SUPPORTS_MARCH=OFF -DCOMPILER_SUPPORTS_MCPU=OFF -DLegion_BUILD_TESTS=ON -DLegion_BUILD_TUTORIAL=ON -DLegion_ENABLE_TESTING=ON ' ' -DLegion_USE_GASNet=OFF ..
RUN make
RUN make test || true
```
and then
```
docker build -t legion_f28 docker/
docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined legion_f28:latest /bin/bash
```
I got
```
gdb bin/attach_file
GNU gdb (GDB) Fedora 8.0.90.20180109-2.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/attach_file...done.
(gdb) run
Starting program: /legion/build/bin/attach_file
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26.9000-51.fc28.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[0 - 7ffff7fea780] {4}{threads}: reservation ('utility proc 0') cannot be satisfied
[New Thread 0x7ffff7fe1700 (LWP 41)]
[New Thread 0x7fffd100a700 (LWP 42)]
[New Thread 0x7ffff7fa0700 (LWP 43)]
[New Thread 0x7fffcbfff700 (LWP 44)]
[New Thread 0x7fffcb7fe700 (LWP 45)]
[0 - 7ffff7fea780] {6}{realm}: invalid processor handle: id=0
attach_file: /legion/runtime/realm/runtime_impl.cc:2402: Realm::ProcessorImpl* Realm::RuntimeImpl::get_processor_impl(Realm::ID): Assertion `0 && "invalid processor handle"' failed.

Thread 1 "attach_file" received signal SIGABRT, Aborted.
0x00007ffff6055f6b in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install hwloc-libs-1.11.8-5.fc28.x86_64 libgcc-8.0.1-0.9.fc28.x86_64 libstdc++-8.0.1-0.9.fc28.x86_64 libtool-ltdl-2.4.6-20.fc27.x86_64 numactl-libs-2.0.11-5.fc27.x86_64
(gdb) bt
#0  0x00007ffff6055f6b in raise () from /lib64/libc.so.6
#1  0x00007ffff6040591 in abort () from /lib64/libc.so.6
#2  0x00007ffff6040461 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007ffff604e6e2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff70bbeaf in Realm::RuntimeImpl::get_processor_impl(Realm::ID) () at /legion/runtime/realm/runtime_impl.cc:2402
#5  0x00007ffff70a3530 in Realm::Processor::kind (this=<optimized out>) at /legion/runtime/realm/runtime_impl.h:312
#6  0x00007ffff70c2865 in Realm::RuntimeImpl::init(int*, char***) () at /legion/runtime/realm/runtime_impl.cc:1502
#7  0x00007ffff7a7f255 in Legion::Internal::Runtime::start(int, char**, bool) () at /legion/runtime/legion/runtime.cc:18462
#8  0x000055555555adbb in main () at /legion/examples/attach_file/attach_file.cc:464
#9  0x00007ffff60421bb in __libc_start_main () from /lib64/libc.so.6
#10 0x000055555555b33a in _start () at /legion/examples/attach_file/attach_file.cc:465
(gdb)
```

**Comment by streichler** [comment]
So I don't have a smoking gun, but this is beginning to look like a compiler bug.  @junghans can you try again with the following patch:
```diff --git a/runtime/realm/id.inl b/runtime/realm/id.inl
index 8fdd114b2..a0675d9c2 100644
--- a/runtime/realm/id.inl
+++ b/runtime/realm/id.inl
@@ -96,7 +96,7 @@ namespace Realm {
     ID id;
     id.rsrv.type_tag = FMT_Reservation::TAG_VALUE;
     id.rsrv.creator_node = creator_node;
-    id.rsrv.unused = 0;
+    //id.rsrv.unused = 0;
     id.rsrv.rsrv_idx = rsrv_idx;
     return id;
   }
@@ -111,7 +111,7 @@ namespace Realm {
     ID id;
     id.memory.type_tag = FMT_Memory::TAG_VALUE;
     id.memory.owner_node = owner_node;
-    id.memory.unused = 0;
+    //id.memory.unused = 0;
     id.memory.mem_idx = mem_idx;
     return id;
   }
@@ -126,7 +126,7 @@ namespace Realm {
     ID id;
     id.memory.type_tag = FMT_IB_Memory::TAG_VALUE;
     id.memory.owner_node = owner_node;
-    id.memory.unused = 0;
+    //id.memory.unused = 0;
     id.memory.mem_idx = mem_idx;
     return id;
   }
```

**Comment by junghans** [comment]
@streichler, that still give me the same error:
```
attach_file: /legion/runtime/realm/runtime_impl.cc:2402: Realm::ProcessorImpl* Realm::RuntimeImpl::get_processor_impl(Realm::ID): Assertion `0 && "invalid processor handle"' failed.
Aborted
```

**Comment by junghans** [comment]
@streichler and here is a koji build with that patch applied: https://koji.fedoraproject.org/koji/taskinfo?taskID=24798360
still failing though.

@lightsighter the above build is using a rebuild of gasnet, so `GASNETI_USE_COMPILER_ATOMICOP` issue on s390x is fixed now.

**Comment by streichler** [comment]
@junghans did the patched version fail for you in that docker image, or just in fedora's automated builds?

**Comment by junghans** [comment]
@streichler it failed in both.

**Comment by streichler** [comment]
hmmm...  Can you try adding `-fno-strict-aliasing` to the CXXFLAGS?  I'll try to reproduce this again on my side as well.

**Comment by junghans** [comment]
Due to `-- Performing Test COMPILER_SUPPORTS_NO_STRICT_ALIASING - Success` this was already the case.

On thing to mention is that Fedora uses:
```
CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection'
```
Maybe one of these default rpm flags isn't good.

**Comment by streichler** [comment]
@junghans are you sure the patch is being applied correctly?  I'm able to reproduce the issue using the Dockerfile above, but when I comment out those three lines of code, everything runs correctly.

**Comment by junghans** [comment]
I rebuild it again at https://koji.fedoraproject.org/koji/taskinfo?taskID=24814678 with an added `cat gcc-8.patch`.

**Comment by streichler** [comment]
In parallel, can you also try applying the patch in the Dockerfile version?  I'm wondering if there's some non-obvious difference between the automated build and the docker version.

**Comment by junghans** [comment]
I applied the patch in both:
```
[root@fe0600476c0d build]# git diff
diff --git a/runtime/realm/id.inl b/runtime/realm/id.inl
index 8fdd114b2..5723dc91b 100644
--- a/runtime/realm/id.inl
+++ b/runtime/realm/id.inl
@@ -96,7 +96,7 @@ namespace Realm {
     ID id;
     id.rsrv.type_tag = FMT_Reservation::TAG_VALUE;
     id.rsrv.creator_node = creator_node;
-    id.rsrv.unused = 0;
+    //id.rsrv.unused = 0;
     id.rsrv.rsrv_idx = rsrv_idx;
     return id;
   }
@@ -111,7 +111,7 @@ namespace Realm {
     ID id;
     id.memory.type_tag = FMT_Memory::TAG_VALUE;
     id.memory.owner_node = owner_node;
-    id.memory.unused = 0;
+    //id.memory.unused = 0;
     id.memory.mem_idx = mem_idx;
     return id;
   }
@@ -126,7 +126,7 @@ namespace Realm {
     ID id;
     id.memory.type_tag = FMT_IB_Memory::TAG_VALUE;
     id.memory.owner_node = owner_node;
-    id.memory.unused = 0;
+    //id.memory.unused = 0;
     id.memory.mem_idx = mem_idx;
     return id;
   }
```

**Comment by streichler** [comment]
Oh, I see the problem...  I missed a few lines when I copy/pasted the patch.  Please add these to the end and try again:
```
@@ -157,7 +157,7 @@ namespace Realm {
     ID id;
     id.proc.type_tag = FMT_Processor::TAG_VALUE;
     id.proc.owner_node = owner_node;
-    id.proc.unused = 0;
+    //id.proc.unused = 0;
     id.proc.proc_idx = proc_idx;
     return id;
   }
```

**Comment by junghans** [comment]
@streichler: Ok that helped on x86_64 (https://koji.fedoraproject.org/koji/taskinfo?taskID=24824176), but ppc64 is still broken:
```
 2/24 Test  #2: circuit ..........................***Exception: Child aborted  2.34 sec
[0 - 7fff5578ed00] {3}{circuit}: circuit settings: loops=2 pieces=4 nodes/piece=2 wires/piece=4 pct_in_piece=95 seed=12345
[0 - 7fff5578ed00] {3}{circuit}: Initializing circuit simulation...
/usr/include/c++/8/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = Realm::Rect<1, long long int>; _Alloc = std::allocator<Realm::Rect<1, long long int> >; std::vector<_Tp, _Alloc>::const_reference = const Realm::Rect<1, long long int>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
*** Caught a fatal signal: SIGABRT(6) on node 0/1
```

**Comment by junghans** [comment]
I just exclude the circuit test on ppc64 and s390x for now and added the above patch:
https://src.fedoraproject.org/rpms/legion/c/cc5e48c883da9d883aa1749a4b3b144d2df257b8?branch=master

So legion-18.02.0 has now arrived in f27 and f28:
https://apps.fedoraproject.org/packages/legion

**Comment by streichler** [comment]
This patch finally made it in to the trea a while ago, and Fedora builds have been working lately.
