### ISSUE TITLE
Build failure in realm/gasnetex with GCC 4.8.5 from RHEL7

### ISSUE THREAD

**Issue by PHHargrove** [StanfordLegion/legion#992]
I am trying to compile the new gasnetex backend for ibv-conduit on a system running Scientific Linux 7.3 (a RHEL 7.3 clone, like CentOS).   On this system, the default compilers in `/usr/bin` identify as `gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)`.  

Since this `g++` defaults to C++98 I have set `CXXFLAGS=-std=c++11`, without which the build fails much earlier than in this report.

The failure I see compiling the `circuit` example is as follows (with paths abbreviated for brevity):
```
mpicxx -o [LEGION_SRC]/runtime/realm/gasnetex/gasnetex_internal.cc.o -c [LEGION_SRC]/runtime/realm/gasnetex/gasnetex_internal.cc  -std=c++11  -march=native -DGASNETI_BUG1389_WORKAROUND=1 -O0 -ggdb  -Wall -Wno-strict-overflow -fvisibility=hidden -fvisibility-inlines-hidden  -I[LEGION_SRC]/examples/circuit -I[LEGION_SRC]/runtime -I[LEGION_SRC]/runtime/mappers -I[GASNETEX_INST]/include -I[GASNETEX_INST]/include/ibv-conduit
In file included from [LEGION_SRC]/runtime/realm/realm_config.h:26:0,
                 from [LEGION_SRC]/runtime/realm/network.h:21,
                 from [LEGION_SRC]/runtime/realm/gasnetex/gasnetex_module.cc:18:
[LEGION_SRC]/runtime/realm/gasnetex/gasnetex_internal.h:222:30: error: requested alignment is not an integer constant
     REALM_ALIGNED_TYPE_CONST(Storage_aligned, Storage_unaligned,
                              ^
[LEGION_SRC]/runtime/realm/compiler_support.h:181:58: note: in definition of macro 'REALM_ALIGNED_TYPE_CONST'
         typedef origtype __attribute__((aligned(bytes))) newtype
                                                          ^
```

I have access to installs of GCC 4.9.4 and 5.1.0 on the same system, and _may_ report on my success or failure with those if I can find time.

**Comment by lightsighter** [comment]
As of our most recent release, Legion and Realm are both requiring c++11 as a minimum version for c++. GCC 4.8's support of c++11 was really flaky, so I wouldn't be surprised if it is not propagating const expressions properly. I would be interested to see what happens with GCC 5.1. Note that even GCC 5.1 is approaching 6 years old in a few months.

**Comment by PHHargrove** [comment]
> I have access to installs of GCC 4.9.4 ...

I have confirmed that builds with GCC 4.9.4, 5.1.0 and 6.4.0 are all error free.

**Comment by lightsighter** [comment]
I think we can just write off GCC 4.8 then as not really c++11 compliant. I'm going to close the issue, but if you would like to us to try to fix it then go ahead and reopen it.

**Comment by streichler** [comment]
Reopening and assigning to me so that I can make sure we write down the supported compiler versions somewhere.

**Comment by PHHargrove** [comment]
Mike,  I didn't actually report this in the hopes you'd work to support this old compiler.  
Sean asked me to enter it to (as he has already noted) help ensure he finds the true floor and documents it.  
However, thanks for the "if you would like us to try..." offer.

**Comment by streichler** [comment]
I have confirmed that we are lacking coverage of Realm's networking code (all of it, not just gasnetex) with g++ 4.8 in our CI tests.  I'm adding tests (in a branch) that I expect to reproduce this failure.  The good news is that a web search has turned up a possible workaround that might be easier than fixing the documentation.  :)

**Comment by lightsighter** [comment]
It's worth noting I'm pushing hard to build out Legion's use of c++11 features for both performance and code-maintainability. I've already found broken c++11 features in older versions of GCC that I've had to disable:

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_utilities.h#L614-617

I would be in favor of just writing off all versions of GCC before 5, since 5 is when the c++11 support actually became solid.

**Comment by streichler** [comment]
Building with g++ 4.8.5 is working again with commits 16e5bb0 and 9f2882a.  We might bump the minimum compiler version at some point, but it doesn't have to be today.

**Comment by PHHargrove** [comment]
Well this is unexpected.  
Since you say 4.8.5 is working once again, I'll plan to resume my CI on RHEL 7.x. once those commits have reached your `stable` branch.
